name: Deploy documentation

# Only trigger on:
# - source branch
on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
    - name: npm run deploy
      run: npm run deploy
      env:
        CI: true
        USE_SSH: true
        GIT_USER: trygve-lie
